version: '3.8'

services:
  ai_engine:
    build:
      context: .
      dockerfile: Dockerfile.ai_engine
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - HF_TOKEN=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
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  flask_server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    depends_on:
      ai_engine:
        condition: service_healthy

networks:
  default:
    driver: bridge